# Basic matrix operations

In [62]:
# Load library
import numpy as np

In [63]:
# Load library
import random
def r():
    return random.randint(0, 5)

In [64]:
# Create 4x3-matrix 
A = np.array([[r() for _ in range(3)] for _ in range(4)])
A

array([[3, 3, 1],
       [2, 0, 0],
       [1, 1, 0],
       [5, 3, 4]])

In [65]:
# Create 3x4-matrix 
B = np.array([[r() for _ in range(3)] for _ in range(4)])
B

array([[5, 3, 2],
       [1, 1, 0],
       [3, 0, 0],
       [2, 1, 3]])

## Addition
When A and B are the same size matrices, We can add or minus them together.

In [66]:
A + B

array([[8, 6, 3],
       [3, 1, 0],
       [4, 1, 0],
       [7, 4, 7]])

## Subtraction

In [67]:
A - B

array([[-2,  0, -1],
       [ 1, -1,  0],
       [-2,  1,  0],
       [ 3,  2,  1]])

## Multiplication
X@Y performs matrix multiplication. Work only when the number of X'columns equals to the number of Y'rows.

In [68]:
A@B.T

array([[26,  6,  9, 12],
       [10,  2,  6,  4],
       [ 8,  2,  3,  3],
       [42,  8, 15, 25]])

In [69]:
B.T@A

array([[30, 24, 13],
       [16, 12,  7],
       [21, 15, 14]])

## Bitwise multiplication
X*Y performs matrix multiplication. Work only when X and Y are same size.

In [70]:
A*B

array([[15,  9,  2],
       [ 2,  0,  0],
       [ 3,  0,  0],
       [10,  3, 12]])

In [71]:
2*A

array([[ 6,  6,  2],
       [ 4,  0,  0],
       [ 2,  2,  0],
       [10,  6,  8]])