# Selecting matrix element

In [36]:
# Load library
import numpy as np
import random

def r():
    return random.randint(0, 5)


In [37]:
# Create 4x3-matrix 
A = np.array([[r() for _ in range(3)] for _ in range(4)])
A

array([[5, 3, 2],
       [2, 5, 4],
       [4, 4, 5],
       [1, 0, 3]])

### Add row to a matrix

In [38]:
# new row
row = np.array([r() for _ in range(3)])
row

array([2, 2, 3])

In [39]:
# Add row to matrix A
A = np.append(A, [row], axis=0)
A

array([[5, 3, 2],
       [2, 5, 4],
       [4, 4, 5],
       [1, 0, 3],
       [2, 2, 3]])

### Add column to a matrix

In [40]:
# new column
column = np.array([[r()] for _ in range(5)])
column

array([[2],
       [0],
       [2],
       [1],
       [5]])

In [41]:
# Add row to matrix A
A = np.append(A, column, axis=1)
A

array([[5, 3, 2, 2],
       [2, 5, 4, 0],
       [4, 4, 5, 2],
       [1, 0, 3, 1],
       [2, 2, 3, 5]])